### ISSUE TITLE
Possible crash between this mod and JEID

### ISSUE THREAD

**Issue by Sunconure11** [mc-jt9/Wards#6] opened 2019-01-23 05:05 UTC
https://pastebin.com/7JMe3jPZ

**Comment by OrderedChaos-Dev** [comment] 2019-02-02 18:23
Sorry for the late reply, I thought I had set notifications when issues are submitted.
I don't see anything pointing to wards being the issue in the crash log. It tags the mod as LCHIJA, which means it loaded correctly. It should have an E if there's something wrong.

**Comment by brisingraerowing** [comment] 2019-05-06 19:26
I get this as well. It most likely is Wards, as the following is in the log right before the crash:

```text
[15:14:26] [Client thread/WARN] [FML]: Registry Potion: Override did not have an associated owner object. Name: wards:effect_smite Value: wards.effect.WardEffect@f107f67
```

**Comment by brisingraerowing** [comment] 2019-05-16 19:10
@mc-jt9

**Comment by OrderedChaos-Dev** [comment] 2019-05-17 20:53
I'll take a look, currently busy with life stuff at the moment, though

**Comment by Laike-Endaril** [comment] 2019-05-23 03:41
I'm getting this as well.  I managed to narrow it down to (at least in my case) an incompatibility between Wards and [DungeonTactics](https://minecraft.curseforge.com/projects/dungeon-tactics?gameCategorySlug=mc-mods&projectID=242500).

With all other 180ish mods enabled, if I disable *only Wards* it runs, or if I enable Wards and disable *only Dungeon Tactics* it runs, but with both mods enabled, it results in this issue.

Also possibly useful info: the warning message ("did not have an associated owner object") is coming from ForgeRegistry.java.  Hopefully you can track the cause from there.  There are two different lines in said file where it could be coming from.

I *think* the root of this particular issue is within Wards, but I'll also create an issue on their side and link the 2 issues together, just in case.

Edit:
[Here's the log file with only Wards and Dungeon Tactics loaded](https://hastebin.com/owulevegey.md)
And [Here's the issue on the Dungeon Tactics tracker](https://minecraft.curseforge.com/projects/dungeon-tactics/issues/82)

**Comment by OrderedChaos-Dev** [comment] 2019-05-24 04:53
The log file is empty, but I'll look into it once I catch a break with the stuff I gotta work on right now.

**Comment by Laike-Endaril** [comment] 2019-05-25 02:21
The log file is showing up fine for me (you meant the link I posted, right?).

If you mean the crash report from the OP, well that one shows up for me too :P

Ofc, if you simply mean there's no particularly useful information, I'd almost have to agree.  The crash itself is just a side-effect, so the crash report has nothing to do with the root issue.  Take a look at this line when you get a chance though:

[20:42:56] [main/WARN] [FML]: Registry Potion: Override did not have an associated owner object. Name: wards:effect_smite Value: wards.effect.WardEffect@42d6aa88

It appears in my log file immediately before the crash, and I guarantee it's what's causing the registry issue (and therefore the crash), at least in my case.

But yeah, don't rush yourself.  You'll just get burnt out if you do.  Happens to me too often

**Comment by OrderedChaos-Dev** [comment] 2019-05-29 04:50
I've released an update that should fix this. I ran an instance of Minecraft with Dungeon Tactics and this mod before and after I made some changes and it seems to have fixed it. Won't close this issue until I'm sure, though.

**Comment by Laike-Endaril** [comment] 2019-05-29 05:12
I can confirm that it no longer crashes on startup for me with Wards 1.3 + Dungeon Tactics.

@Sunconure11 @BrisingrAerowing Maybe you can both test the new version in the environments you had crashes in, and see if it's fixed for you as well

**Comment by OrderedChaos-Dev** [comment] 2019-05-29 05:22
I just uploaded 1.3.1 a few minutes ago because I was being stupid and forgot to actually make the new enchanted paper do stuff. If you go ahead and download that (lol) you'll get the actual updated version.
Just like what my boss told me a few days ago: "The difference between a good programmer and a great programmer is that the great programmer has made far more mistakes"

**Closed as completed by OrderedChaos-Dev** 2019-05-29 05:22 UTC
